[cabal]
patterns = ["dist-newstyle/"]

[cabal.detect]
suffix = [".cabal"]

[cargo]
priority = 0
patterns = [
    "target/",
    ".xwin-cache/",
]

[cargo.detect]
suffix = [".rs"]

[cmake]
patterns = [
    "build/",
    "cmake-build-debug/",
    "cmake-build-release/",
]

[cmake.detect]
suffix = [".cmake"]
names = ["cmakelists.txt"]

[cocoapods]
patterns = ["Pods/"]

[common]
patterns = [
    "tmp/",
    "temp/",
    "*.tmp",
    "*.temp",
    ".DS_Store",
    "Thumbs.db",
    "*.swp",
    "*.swo",
    "*~",
    ".*.un~",
]

[composer]
patterns = ["vendor/"]

[composer.detect]
suffix = [".php"]

[dotnet]
patterns = [
    "bin/",
    "obj/",
]

[dotnet.detect]
suffix = [
    ".cs",
    ".csx",
    ".fs",
    ".fsi",
    ".fsx",
    ".fsscript",
    ".csproj",
    ".vbproj",
    ".fsproj",
    ".props",
    ".targets",
]

[elixir]
patterns = [
    "_build/",
    ".elixir-tools/",
    ".elixir_ls/",
    ".lexical/",
]

[elixir.detect]
suffix = [
    ".ex",
    ".exs",
]

[godot4]
patterns = [".godot/"]

[godot4.detect]
suffix = [
    ".gd",
    ".cs",
    ".csx",
]

[gradle]
patterns = [
    "build/",
    ".gradle/",
]

[gradle.detect]
suffix = [
    ".groovy",
    ".grt",
    ".gtpl",
    ".gvy",
    ".kt",
    ".kts",
    ".java",
]
env = ["groovy"]

[jupyter]
patterns = [".ipynb_checkpoints/"]

[jupyter.detect]
suffix = [".ipynb"]

[latex]
require-ancestor = true
patterns = [
    "_minted-*/",
    "*.aux",
    "*.log",
    "*.out",
    "*.toc",
    "*.lof",
    "*.lot",
    "*.fdb_latexmk",
    "*.fls",
    "*.synctex.gz",
    "*.blg",
    "*.run.xml",
    "*.bcf",
]

[latex.detect]
suffix = [
    ".tex",
    ".sty",
]

[maven]
patterns = ["target/"]

[maven.detect]
suffix = [".java"]

[node]
priority = 0
patterns = [
    "node_modules/",
    ".angular/",
]

[node.detect]
suffix = [
    ".cjs",
    ".js",
    ".mjs",
    ".ts",
    ".mts",
    ".cts",
]
env = ["node"]
shebang = [
    "#!/usr/bin/env node",
    "#!/usr/bin/node",
]

[pixi]
patterns = [".pixi/"]

[pixi.detect]
suffix = [
    ".py",
    ".pyw",
    ".pyi",
]
env = [
    "python",
    "python2",
    "python3",
]

[pub]
patterns = [
    "build/",
    ".dart_tool/",
    "linux/flutter/ephemeral/",
    "windows/flutter/ephemeral/",
]

[pub.detect]
suffix = [".dart"]

[python]
priority = 0
patterns = [
    ".mypy_cache/",
    ".nox/",
    ".pytest_cache/",
    ".ruff_cache/",
    ".tox/",
    "__pycache__/",
    "__pypackages__/",
    "venv/",
    ".venv/",
    "env/",
    ".env/",
    ".uv-cache/",
    ".uv-cache/**",
    "build/",
    "*.pyc",
]

[python.detect]
suffix = [
    ".py",
    ".pyw",
    ".pyi",
]
env = [
    "python",
    "python2",
    "python3",
]

[react]
patterns = [
    "dist/",
    "build/",
    "coverage/",
    ".next/",
]

[react.detect]
suffix = [
    ".jsx",
    ".tsx",
]

[reactnative]
patterns = [
    "node_modules/",
    "android/build/",
    "android/.gradle/",
    "ios/build/",
    "ios/DerivedData/",
    "ios/Pods/",
    ".expo/",
    ".metro/",
]

[reactnative.detect]
suffix = [
    ".cjs",
    ".js",
    ".mjs",
    ".ts",
    ".mts",
    ".cts",
    ".jsx",
    ".tsx",
]

[sbt]
patterns = [
    "target/",
    "project/target/",
]

[sbt.detect]
suffix = [
    ".sc",
    ".scala",
]

[stack]
patterns = [".stack-work/"]

[stack.detect]
suffix = [".hs"]

[swift]
patterns = [
    ".build/",
    ".swiftpm/",
]

[swift.detect]
suffix = [".swift"]

[terraform]
patterns = [".terraform/"]

[terraform.detect]
suffix = [
    ".hcl",
    ".tf",
    ".tfvars",
]

[turborepo]
patterns = [".turbo/"]

[turborepo.detect]
suffix = [
    ".cjs",
    ".js",
    ".mjs",
    ".ts",
    ".mts",
    ".cts",
    ".jsx",
    ".tsx",
]

[unity]
patterns = [
    "Library/",
    "Temp/",
    "Obj/",
    "Logs/",
    "MemoryCaptures/",
    "Build/",
    "Builds/",
]

[unity.detect]
suffix = [
    ".cs",
    ".csx",
]

[unreal]
patterns = [
    "Binaries/",
    "Build/",
    "Saved/",
    "DerivedDataCache/",
    "Intermediate/",
]

[unreal.detect]
suffix = [
    ".uproject",
    ".uplugin",
    ".uc",
    ".uci",
    ".upkg",
]

[zig]
patterns = [
    "zig-cache/",
    ".zig-cache/",
    "zig-out/",
]

[zig.detect]
suffix = [".zig"]
